### ISSUE TITLE
Error when trying to run?

### ISSUE THREAD

**Issue by daven1985** [jmeischner/alfred-bear-daily-log#2]
Sorry I am not good at this stuff.

![image](https://user-images.githubusercontent.com/18471680/89143847-4a313580-d58f-11ea-8d96-a8e32277f6ce.png)

```
david.nichols@dni .bear-templates % npm install
npm WARN bear-template-daily-log@0.0.1 No repository field.

added 1 package from 1 contributor and audited 1 package in 0.531s
found 0 vulnerabilities

david.nichols@dni .bear-templates % 

```

When I try and run it error of...
```
TypeError: Cannot read property 'map' of undefined
    at getTemplates (/usr/local/lib/node_modules/alfred-bear/bear-template/index.js:34:26)
    at /usr/local/lib/node_modules/alfred-bear/bear-template/index.js:52:19
    at Object.<anonymous> (/usr/local/lib/node_modules/alfred-bear/bear-template/index.js:56:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/alfred-bear/node_modules/esm/esm.js:1:251206)
    at /usr/local/lib/node_modules/alfred-bear/node_modules/esm/esm.js:1:245054
    at Generator.next (<anonymous>)
    at bl (/usr/local/lib/node_modules/alfred-bear/node_modules/esm/esm.js:1:245412)
    at kl (/usr/local/lib/node_modules/alfred-bear/node_modules/esm/esm.js:1:247659)
    at Object.u (/usr/local/lib/node_modules/alfred-bear/node_modules/esm/esm.js:1:287740)
    at Object.o (/usr/local/lib/node_modules/alfred-bear/node_modules/esm/esm.js:1:287137)
```

-
Bear Templates 0.2.4
Alfred 4.1
darwin 19.5.0

**Comment by jmeischner** [comment]
Hej @daven1985,

thanks for bringing this up ☺️

I would propose to not have the template files for such scripted templates in its own directory, so that the directory structure becomes more clear.

Then it would look like this:
<img width="234" alt="Bildschirmfoto 2020-08-03 um 09 35 48" src="https://user-images.githubusercontent.com/7792451/89157379-b9496280-d56c-11ea-969f-be7e115f735b.png">

Now your `index.yml` should look like this:

```yaml
templates:
  - title: Daily Log
    file: "daily log/Daily Log.md"
    script: "daily log/script.js"
    newWindow: true
    var:
      DATE_FORMAT: "ddd., DD MMM. YYYY"
```

where `daily log/Daily Log.md` is the path to the markdown file and the `daily log/script.js` is the path to the script file relative to the *index.yml*.

I would guess in your case you maybe missed the `templates` line in the *index.yml*, could this be?

**Comment by daven1985** [comment]
Mate your a legend... that work brilliantly.

Can I ask one more call for help... where you have log for that day... I like to keep my notes sorted weekly. Is there a way to have it insert the Monday for Each week there... 

![image](https://user-images.githubusercontent.com/18471680/89169815-1ae7ec00-d5c2-11ea-8255-a9032b90942b.png)

So basically for all of this week each Log has #log/2020/08/03 at the top.

Cheers.

**Comment by jmeischner** [comment]
The used log for that day is part of the **Daily Log.md** file. There you have the third line as something like this `#daily-log/{date: YYYY/MM/dd}` which uses the [Alfred functionality to work with dates](https://www.alfredapp.com/help/workflows/advanced/placeholders/#date-time). 

For your specific problem I would have two solution in mind.

First would be to just use the *week of the year*.
This you can achieve by replacing the bespoken line with
```md
#log/{date: YYYY/w}
#log/{date: YYYY/MM/w}
```
then you get something like `#log/2020/32` or `#log/2020/08/32`

or the second solution is to replace your `script.js` file with the following content:

```js
const date = require('date-and-time');

function getDiffToLastMonday(today) {
  switch(today) {
    case 'Mo':
      return 0;
      break;
    case 'Tu':
      return -1;
      break;
    case 'We':
      return -2;
      break;
    case 'Th':
      return -3;
      break;
    case 'Fr':
      return -4;
      break;
    case 'Sa':
      return -5;
      break;
    case 'Su':
      return -6;
      break;
    
  }

}

function getDiffToLastWorkday(today) {
  switch (today) {
    case 'Mo':
      return -3;
      break;
    case 'Su':
      return -2;
      break;
    default:
      return -1;
      break;
  }
}

function getDiffToNextWorkday(today) {
  switch (today) {
    case 'Fr':
      return 3;
      break;
    case 'Sa':
      return 2;
      break;
    default:
      return 1;
      break;
  }
}


function getData(variables) {
  const format = variables.DATE_FORMAT;
  const now = new Date();
  const weekday = date.format(now, 'dd');
  const nextDiff = getDiffToNextWorkday(weekday);
  const lastDiff = getDiffToLastWorkday(weekday);
  const mondayDiff = getDiffToLastMonday(weekday);

  const today = date.format(now, format);
  const next = date.format(date.addDays(now, nextDiff), format);
  const last = date.format(date.addDays(now, lastDiff), format);
  const monday = date.format(date.addDays(now, mondayDiff), 'YYYY/MM/DD');

  return {
    today: today,
    last: last,
    next: next,
    monday: monday
  }
}

module.exports = getData;
```

and then you can replace the bespoken line with

```md
#log/{{monday}}
```

this would exactly give you the *monday-solution* ☺️

**Comment by daven1985** [comment]
Mate that is awesome! I can't thank you enough!

![image](https://user-images.githubusercontent.com/18471680/89226203-eeae8880-d61e-11ea-825e-52a53b6b518c.png)

Here is what mine looks like! I love it!

If I can push my friendship... one last question? How do I change the ::[[Mon., 03 Aug. 2020]]:: <- -> ::[[Wed., 05 Aug. 2020]]:: to match my new format.

I assume it is the script.js area... I am just not sure what part to actually change.

**Comment by jmeischner** [comment]
Glad that it works 😊

I tried to make this format easily customizable, that's why it is part of the **index.yml** 😅

```yml
templates:
  - title: Daily Log
    file: "daily log/Daily Log.md"
    script: "daily log/script.js"
    newWindow: true
    var:
      DATE_FORMAT: "ddd., DD MMM. YYYY"
```

So to have something like `August 4, 2020` you need to change it to `MMMM D, YYYY` 👍 this is then applied to the Title and the two links in `[[<date>]]` because bear links to other notes by the title of the note, so these needs to match.

**Comment by daven1985** [comment]
Mate you rock!

Unless you object I wouldn't post it on the Bear Reddit how awesome this is... of course giving you the credit!
